### ISSUE TITLE
Monthly Attendance Sheet

### ISSUE THREAD

**Issue by bidish** [JayVora-SerpentCS/OdooEduERP#110]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/demo/demo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/demo/demo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/demo/demo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/demo/demo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/demo/demo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/demo/demo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/demo/demo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/demo/demo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/demo/demo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/demo/demo-server/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/demo/demo-server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/demo/demo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/demo/demo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/demo/demo-server/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/demo/demo-server/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/demo/custom/addons/school_attendance/models/school_attendance.py", line 80, in fields_view_get
    res['fields']['attendance_ids']['views']['tree']['fields'][digits_temp_dict.get(flag)]['string'] = st_dates.day
KeyError: None

**Comment by JayVora-SerpentCS** [comment]
@Arpit-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
Help us with the steps too.

**Comment by bidish** [comment]
Steps to reproduce:

Go to Attendance
Select Monthly Attendance Sheet
Fill in the information
Click on Open Attendance Sheet.

**Comment by Arpit-SerpentCS** [comment]
@bidish I have tested the issue that you have mentioned regarding the attendance module,  but I did not got any traceback when clicked on  Open Attendance Sheet button after filling details in monthly attendance sheet. Please explain the steps with more details

**Comment by bidish** [comment]
@Arpit-SerpentCS Maybe I am doing something wrongly here but the issue persists. I always get error when I fill in the monthly attendance sheet and click on open attendance sheet. Has it got anything to do with enterprise or community?

**Comment by Arpit-SerpentCS** [comment]
@bidish we have tested in the odoo 10/11 community version.Please tell us on which environment you are working?
