### ISSUE TITLE
Error message shown when trying to create new teacher.

### ISSUE THREAD

**Issue by HarrySG** [JayVora-SerpentCS/OdooEduERP#14]
Odoo Server Error
Traceback (most recent call last):
  File "/home/harry/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/harry/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/harry/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/harry/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/harry/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/harry/odoo/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/harry/odoo/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/harry/odoo/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/harry/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/harry/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 5996, in onchange
    record = self.new(values)
  File "/home/harry/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 5563, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/home/harry/odoo/openerp/models.py", line 5458, in _convert_to_cache
    for name, value in values.iteritems()
  File "/home/harry/odoo/openerp/models.py", line 5459, in <dictcomp>
    if name in fields
  File "/home/harry/odoo/openerp/fields.py", line 1743, in convert_to_cache
    ids = OrderedSet(record[self.name].ids)
  File "/home/harry/odoo/openerp/models.py", line 5720, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/harry/odoo/openerp/fields.py", line 827, in **get**
    self.determine_draft_value(record)
  File "/home/harry/odoo/openerp/fields.py", line 940, in determine_draft_value
    self._compute_value(record)
  File "/home/harry/odoo/openerp/fields.py", line 876, in _compute_value
    getattr(records, self.compute)()
  File "/home/harry/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/api.py", line 425, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/home/harry/odoo/eduerp/school/models/school.py", line 641, in _compute_subject
    subject_ids = subject_obj.search([('teacher_ids.id', '=', self.id)])
  File "/home/harry/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/harry/odoo/eduerp/timetable/models/timetable.py", line 80, in search
    count=count)
  File "/home/harry/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 1657, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/harry/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 4744, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/home/harry/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 4515, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/home/harry/odoo/openerp/osv/expression.py", line 644, in __init__
    self.parse(cr, uid, context=context)
  File "/home/harry/odoo/openerp/osv/expression.py", line 881, in parse
    right_ids = comodel.search(cr, uid, [(path[1], operator, right)], context=context)
  File "/home/harry/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 1657, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/harry/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/models.py", line 4762, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/harry/odoo/openerp/sql_db.py", line 139, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/harry/odoo/openerp/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: can't adapt type 'NewId'

**Comment by JayVora-SerpentCS** [comment]
Which version are you using?
Thanks.
