### ISSUE TITLE
ERROR installing eduerp_base and school_evaluation

### ISSUE THREAD

**Issue by rithin** [JayVora-SerpentCS/OdooEduERP#144]
Hi Team,
When i'm trying to install eduerp_base am getting the following error. Can you please give some hits to fix the problem
  I installed almost all the supporting modules but evaluation module is throwing some errors as well as the edu ERP_base also throwing some error while on installation. 

> Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 194, in load_module_graph
    registry.setup_models(cr)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 267, in setup_models
    model._setup_fields()
  File "/opt/odoo12/odoo/odoo/models.py", line 2609, in _setup_fields
    field.setup_full(self)
  File "/opt/odoo12/odoo/odoo/fields.py", line 482, in setup_full
    self._setup_regular_full(model)
  File "/opt/odoo12/odoo/odoo/fields.py", line 2392, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'message_id'

>

**Comment by JayVora-SerpentCS** [comment]
@AnuKPatel Please take a look, thanks.

**Comment by AnuKPatel** [comment]
@rithin We have successfully installed the eduerp_base with all the dependent modules at our end with latest source code of odoo 12.

Can you please check once again by pull the latest source code of odoo?

Let us know if you are still facing issues.

**Comment by rithin** [comment]
@AnuKPatel , Thanks for the response. 
I have pulled the latest code of odoo and use the latest code of edu_erp aswell. But still, am getting the same error. If you want the login information of server, I have already sent it to Yogendrasinh.

Regards,
RIthin

**Comment by JayVora-SerpentCS** [comment]
@YogendrasinhChavda do you have update here?

**Comment by YogendrasinhChavda** [comment]
I passed information to Jagdish Panchal, he will work on it.

**Comment by JayVora-SerpentCS** [comment]
I am closing as this doesnot happen in usual instances. We may reopen if found issues.

**Comment by JayVora-SerpentCS** [comment]
@JagdishPanchalSCS the issue comes because RATING module of odoo conflicts with ours.
Looks like odoo added modules since v12.
Let's have a word on Monday.
Thanks.

**Comment by JagdishPanchalSCS** [comment]
@JayVora-SerpentCS yes I have traced in local and found it in school_evaluation module.

**Comment by JayVora-SerpentCS** [comment]
Do check our gitlab where its a matter of _inherits, or make a check we
might not need our rating module.

**Comment by AnuKPatel** [comment]
@JagdishPanchalSCS Can you please update us, this issue is fixed or not? If fixed we can close this issue.

**Comment by JagdishPanchalSCS** [comment]
@AnuKPatel Yes fixed alredy.
