### ISSUE TITLE
Odoo Server Error : during Exam management installation

### ISSUE THREAD

**Issue by leo-ndl** [JayVora-SerpentCS/OdooEduERP#161]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 655, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1517, in _update
    record = record.create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3435, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3513, in _create
    self._check_selection_field_value(name, val)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 2123, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1831, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for time.table.line.week_day: 'vendredi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\module\module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\module\module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\module\module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 184, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 792, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 853, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 742, in parse
    self.parse(rec, mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 752, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\convert.py", line 655, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_model.py", line 1517, in _update
    record = record.create(values)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3435, in create
    record = self.browse(self._create(old_vals))
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 3513, in _create
    self._check_selection_field_value(name, val)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 2123, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\fields.py", line 1831, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
odoo.tools.convert.ParseError: "Wrong value for time.table.line.week_day: 'vendredi'" while parsing file:/c:/program%20files%20(x86)/odoo%2011.0/server/odoo/addons/exam/demo/exam_demo.xml:29, near
<record id="time_table_line_0" model="time.table.line">
            <field name="teacher_id" ref="school.demo_school_teacher_1"/>
            <field name="subject_id" ref="school.demo_subject_subject_1"/>
            <field name="exm_date" eval="time.strftime('%Y')+'/03/06'"/>
            <field name="week_day" eval="DateTime.strptime((time.strftime('%Y')+'/03/06'), '%Y/%m/%d').strftime('%A').lower()"/>
            <field model="time.table" name="table_id" search="[('name', '=', u'Final Exam Timetable')]"/>
            <field eval="12.0" name="end_time"/>
            <field eval="10.0" name="start_time"/>
        </record>
PS: I need help to solve this issue.

**Comment by JayVora-SerpentCS** [comment]
@Freni-SerpentCS Can you quickly check to help @leo-gtx ?
Do we have venderdi on demo data?
"Wrong value for time.table.line.week_day: 'vendredi'"

**Comment by JayVora-SerpentCS** [comment]
We will reopen when info is provided. Till then, better is to use latest version.
Thanks,
