### ISSUE TITLE
have a issues when install module school in odoo13

### ISSUE THREAD

**Issue by lyprono** [JayVora-SerpentCS/OdooEduERP#167]
i have a issues when i install module school in odoo13 community ( Many2many fields school.teacher.category_ids and hr.employee.category_ids use the same table and columns) however i have to deleted hr module but it still have gotten error 
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 201, in load_module_graph
    registry.setup_models(cr)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 255, in setup_models
    model._setup_fields()
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 2693, in _setup_fields
    field.setup_full(self)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 431, in setup_full
    self._setup_regular_full(model)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\fields.py", line 3252, in _setup_regular_full
    raise TypeError(msg % (self, field))
TypeError: Many2many fields school.teacher.category_ids and hr.employee.category_ids use the same table and columns

**Comment by JayVora-SerpentCS** [comment]
@Freni-SerpentCS Plz check

**Comment by lyprono** [comment]
Thank i have fixed this error however it still have gotten in view .this module supported  for odoo13 because have alot error code with odoo13
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4083, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3997, in _load_records_create
    return self.create(values)
  File "<decorator-gen-36>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 235, in create
    return super(IrActionsActWindow, self).create(vals_list)
  File "<decorator-gen-34>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 59, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3702, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'view_type' on model 'ir.actions.act_window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\modules\loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 721, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 712, in parse
    self._tag_root(de)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 674, in _tag_root
    f(rec)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\tools\convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 4083, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3997, in _load_records_create
    return self.create(values)
  File "<decorator-gen-36>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 235, in create
    return super(IrActionsActWindow, self).create(vals_list)
  File "<decorator-gen-34>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\addons\base\models\ir_actions.py", line 59, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files (x86)\Odoo 13.0\server\odoo\models.py", line 3702, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
odoo.tools.convert.ParseError: "Invalid field 'view_type' on model 'ir.actions.act_window'" while parsing file:/c:/program%20files%20(x86)/odoo%2013.0/server/odooeduerp/school/wizard/terminate_reason_view.xml:3, near
<odoo>
    <data>
        
        <record id="school_terminate_reason" model="ir.ui.view">
            <field name="name">Terminate Reason</field>
            <field name="model">terminate.reason</field>
            <field name="arch" type="xml">
                <form string="Terminate Wizard">
                    <sheet>
                        <group>
                            <field name="reason" required="1" nolabel="1" placeholder="Reason"/>
                         </group>
                        <footer>
                            <button name="save_terminate" string="Terminate" type="object"/>
                            <button special="cancel" string="Cancel"/>
                        </footer>
                    </sheet>
                </form>
            </field>
        </record>
        
        <record id="action_terminate_wizard" model="ir.actions.act_window">
            <field name="name">Termination Reason</field>
            <field name="res_model">terminate.reason</field>
            <field name="view_type">form</field>
            <field name="view_mode">form</field>
            <field name="target">new</field>
        </record>
    </data>
</odoo>

**Comment by lyprono** [comment]
hello sir 
this is module have supported in odoo13?

**Comment by JayVora-SerpentCS** [comment]
I assume v13 code is not pushed or published. @AnuKPatel  ?

**Comment by lyprono** [comment]
can you share  v13?

**Comment by JayVora-SerpentCS** [comment]
yes just v13 is uploaded. Thanks,
