### ISSUE TITLE
"Odoo server error" when the create button is clicked

### ISSUE THREAD

**Issue by jessekobe** [JayVora-SerpentCS/OdooEduERP#27]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 862, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 854, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 679, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 664, in call_kw_model
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1112, in default_get
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\school\models\school.py", line 330, in <lambda>
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\school\models\school.py", line 314, in _get_default_image
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\image.py", line 212, in image_colorize
  File "PIL\Image.pyc", line 2025, in open
IOError: cannot identify image file

**Comment by JayVora-SerpentCS** [comment]
Hello @jessekobe , please pull the latest version.
