### ISSUE TITLE
Error when install Evaluation Management

### ISSUE THREAD

**Issue by W360S** [JayVora-SerpentCS/OdooEduERP#37]
Hello i have install all of school module it work, but when i try to install Evaluation Management it show me that. plz help
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 135, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 293, in setup_models
    model._setup_fields(partial)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 2836, in _setup_fields
    field.setup_full(self)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 491, in setup_full
    self._setup_related_full(model)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 529, in _setup_related_full
    field.setup_full(target)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 491, in setup_full
    self._setup_related_full(model)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 529, in _setup_related_full
    field.setup_full(target)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 489, in setup_full
    self._setup_regular_full(model)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 2125, in _setup_regular_full
    invf = comodel._fields[self.inverse_name]
KeyError: 'res_id'

**Comment by JayVora-SerpentCS** [comment]
Checking soon.

**Comment by AnuKPatel** [comment]
Hello @W360S 

We have installed Evaluation Management(**branch-10.0**) in new database with latest code of **Odoo v10**, but can't regenerate the issue.
It will be helpful for us if you provide the details to confirm whether we are in the same boat or not.

Thanks.

**Comment by W360S** [comment]
hello plz check here you will see the error http://school-demo2.wcloud.vn/ user: demo/demo
nevermind about info, this is demo one, i will deleted db in short future.

**Comment by AnuKPatel** [comment]
Hello @W360S ,

Thanks for the details. We'll check and update you ASAP.

**Comment by AnuKPatel** [comment]
Helllo @W360S ,

We have checked with given credentials. There is no issue while installing Evaluation Management. We have successfully installed it at your end. but we found an issue while installing Transport management because of the base odoo have not latest code.

Currently we have installed all the modules of School Category at your end, but please pull the latest code of odoo v10 before installing the modules in new db.

Hope this will help you! Please let us know if you face any issue.

Thanks!

**Comment by JayVora-SerpentCS** [comment]
Request to check with the latest commits. Revert back if the problem still appears.
