### ISSUE TITLE
installation error when tried to install with demo data

### ISSUE THREAD

**Issue by odoouser2** [JayVora-SerpentCS/OdooEduERP#43]
Odoo 10

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 866, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 854, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 681, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 672, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 410, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 484, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\registry.py", line 78, in new
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 337, in load_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 235, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 159, in load_module_graph
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 95, in _load_data
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 848, in convert_file
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 918, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 799, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 802, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 710, in _tag_record
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_model.py", line 1159, in _update
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\school\models\school.py", line 330, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3804, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3892, in _create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\sql_db.py", line 141, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\sql_db.py", line 218, in execute
ParseError: "date/time field value out of range: "02/14/2001"
LINE 1: ...'Joseph', false, 2, false, false, false, 'draft', '02/14/200...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
" while parsing file:///C:/Program%20Files%20(x86)/Odoo%2010.0/server/odoo/addons/school/demo/school_demo.xml:554, near
<record id="demo_student_student_2" model="student.student">
            <field name="name">William</field>
            <field name="middle">Joseph</field>
            <field name="last">Lee</field>
            <field name="state">draft</field>
            <field name="year" ref="demo_academic_year_2"/>
            <field name="pid">2016/08</field>
            <field name="date_of_birth">02/14/2001</field>
            <field name="gender">male</field>
            <field name="roll_no">1</field>
            <field name="school_id" ref="demo_school_1"/>
            <field name="country_id" ref="base.au"/>
            <field name="city">Sydney</field>
            <field name="standard_id" ref="demo_standard_standard_2"/>
            <field name="division_id" ref="demo_standard_division_2"/>
            <field name="medium_id" ref="demo_standard_medium_2"/>
        </record>

**Comment by odoouser2** [comment]
Without demo data it worked fine but error with demo data.

**Comment by JayVora-SerpentCS** [comment]
Surely an error with date type.

**Comment by JayVora-SerpentCS** [comment]
@arpit983

**Comment by Arpit-SerpentCS** [comment]
solved

**Comment by JayVora-SerpentCS** [comment]
#48 closed.
