### ISSUE TITLE
Error while creating School on fresh database but work fine with demo data

### ISSUE THREAD

**Issue by dansputy** [JayVora-SerpentCS/OdooEduERP#45]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo10/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo10/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo10/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo10/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo10/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo10/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo10/odoo/models.py", line 3823, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo10/odoo/models.py", line 3884, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/opt/odoo10/addons/stock/models/res_company.py", line 37, in create
    self.env['stock.warehouse'].sudo().create({'name': company.name, 'code': company.name[:5], 'company_id': company.id})
  File "/opt/odoo10/addons/stock/models/stock_warehouse.py", line 90, in create
    vals['view_location_id'] = self.env['stock.location'].create(loc_vals).id
  File "/opt/odoo10/odoo/models.py", line 3823, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo10/odoo/models.py", line 3943, in _create
    pleft = cr.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by JayVora-SerpentCS** [comment]
@arpit983 please check it.

**Comment by JayVora-SerpentCS** [comment]
Closed by #46

**Comment by JayVora-SerpentCS** [comment]
#48
