### ISSUE TITLE
Error when trying to install School Module

### ISSUE THREAD

**Issue by LuiggiMS** [JayVora-SerpentCS/OdooEduERP#70]
Hi. I tried to install School Module in a clean installation of Odoo 11.0 (Community Edition)

But I received this error, related to Model 'report'. 
Traceback (most recent call last):
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/luiggi/Desktop/enviroment-python/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/modules/loading.py", line 130, in load_module_graph
    model_names = registry.load(cr, package)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/modules/registry.py", line 252, in load
    model = cls._build_model(self, cr)
  File "/Users/luiggi/Desktop/enviroment-python/odoo/odoo/models.py", line 428, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'report' does not exist in registry.

**Comment by JayVora-SerpentCS** [comment]
Did you try with latest source? We have removed this from v11 already.
