### ISSUE TITLE
Error installing module "Attendance Management" in Odoo 11.0

### ISSUE THREAD

**Issue by LuiggiMS** [JayVora-SerpentCS/OdooEduERP#87]
I have successfully install module 'School' but after that when I try to install module "Attendance Management" It appear a error. It seems there is a problem with the model 'ir.needaction_mixin'.

`Traceback (most recent call last):
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/modules/loading.py", line 130, in load_module_graph
    model_names = registry.load(cr, package)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/modules/registry.py", line 252, in load
    model = cls._build_model(self, cr)
  File "/Users/luiggi/Desktop/enviroment-python/odoo-11.0/odoo/models.py", line 447, in _build_model
    raise TypeError("Model %r inherits from non-existing model %r." % (name, parent))
TypeError: Model 'studentleave.request' inherits from non-existing model 'ir.needaction_mixin'.`

**Comment by JayVora-SerpentCS** [comment]
Doesn't seem to happen with our set of modules. Please recheck with latest source, and also make sure any 3rd party app does not conlfict.
